name: 🧼 Merge Clean Temp to Data

on:
  push:
    paths:
      - 'dynamic/temp.json'

jobs:
  merge-temp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run merge script
        run: node dynamic/merge-temp-to-data.js

      - name: Commit cleaned data.json
        run: |
          git config user.name "Merge Bot"
          git config user.email "bot@sellinseconds.in"
          git add dynamic/data.json
          git commit -m "✅ Auto-merge cleaned temp.json into data.json"
          git push