name: Update OG Meta Tags

on:
  push:
    paths:
      - 'dynamic/data.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Generate updated HTML
        run: |
          node dynamic/generate-html-with-versioned-images.js

      - name: Commit changes
        run: |
          git config user.name "OG Meta Bot"
          git config user.email "bot@sellinseconds.in"
          git add dynamic/buygallery.html
          git commit -m "Auto-update OG meta from data.json" || echo "No changes"
          git push || echo "Already up to date"
